<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]>
<html lang="en"4>
<!--<![endif]-->

<!-- 头部开始 -->
<head>
    {{ partial('layouts/header') }}
</head>
<!-- 头部结束 -->

<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">
<!-- 顶部开始 -->
{{ partial('layouts/top_sidebar') }}
<!-- 顶部结束 -->
<div class="clearfix"> </div>

<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- 左侧菜单开始 -->
    {{ partial('layouts/left_sidebar') }}
    <!-- 左侧菜单结束 -->

    <!-- BEGIN CONTENT -->
    {{content()}}
    <!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- 尾部开始 -->

<!-- 尾部结束 -->
<!--[if lt IE 9]>

<script src="{{static_url('assets/global/plugins/respond.min.js')}}"></script>
<script src="{{static_url('assets/global/plugins/excanvas.min.js')}}"></script>
<![endif]-->

<script src="{{static_url('assets/global/plugins/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/jquery.blockui.min.js')}}" type="text/javascript"></script>
<!--  表单美化插件 -->
<script src="{{static_url('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}" type="text/javascript"></script>

<!--  日期处理插件 -->
<script src="{{static_url('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/moment.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/scripts/app.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/layouts/layout/scripts/layout.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/layouts/layout/scripts/demo.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/layouts/global/scripts/quick-sidebar.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/layer/layer.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/scripts/submit.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/scripts/dateFilter.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/scripts/del.js')}}" type="text/javascript"></script>
<!-- END THEME LAYOUT SCRIPTS -->
</body>

</html>