<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="/admin/index/index">首页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="/admin/channel/index">渠道列表</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="/admin/channel/channelInfo?id=<?= $cid ?>">渠道信息</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span><?= $title ?>支付方式</span>
                    <i class="fa fa-circle"></i>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bubble font-green-sharp"></i>
                            <span class="caption-subject font-green-sharp sbold"><?= $title ?>渠道</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form class="form-horizontal" id="save" url="/admin/channel/channelInfoSave" method="post">
                            <input type="hidden" name="id" value="<?= $data->id ?? ''?>">
                            <input type="hidden" name="channel_id" value="<?= $cid ?? ''?>">
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    支付方式
                                    <span class="required" aria-required="true">*</span>
                                </label>
                                <div class="col-md-5">
                                    <select class="bs-select form-control" name="pay_id">
                                        <?php foreach ($pay_arr as $pay): ?>
                                            <option value="<?=$pay['id']?>"  <?= isset($data->pay_id) && $data->pay_id == $pay['id'] ?  'selected': ''?> ><?= $pay['name']?></option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    支付值
                                    <span class="required" aria-required="true">*</span>
                                </label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control"  name="pay_name"  value="<?= $data->pay_name ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    支付最大额度
                                    <span class="required" aria-required="true">*</span>
                                </label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" name="max" value="<?= $data->max ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    支付最少额度
                                    <span class="required" aria-required="true">*</span>
                                </label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control"  name="min" value="<?= $data->min ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">是否开启</label>
                                <div class="col-md-5">
                                    <input type="checkbox" class="make-switch" name="status" <?=  isset($data->status) && $data->status == 1 ? 'checked' : !isset($data->status) ? 'checked': ''?>
                                           data-size="large"  data-on-color="info" data-off-color="success">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title"></label>
                                <div class="col-md-5">
                                    <button type="button" id="submit" class="btn green btn-circle">
                                        <i class="fa fa-check"></i> 保存
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END CONTENT BODY -->
</div>
