<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="/admin/index/index">首页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="/admin/channel/index">渠道列表</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <span><?= $title ?>渠道</span>
                    <i class="fa fa-circle"></i>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bubble font-green-sharp"></i>
                            <span class="caption-subject font-green-sharp sbold"><?= $title ?>渠道</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <form class="form-horizontal" id="save" url="/admin/channel/save" action="/admin/channel/save" method="post">
                            <input type="hidden" name="id" value="<?= $data->id ?? ''?>">
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    渠道名称:
                                    <span class="required" aria-required="true">*</span>
                                </label>

                                <div class="col-md-5">
                                    <input type="text" class="form-control" name="name" value="<?= $data->name ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    支付渠道值:
                                    <span class="required" aria-required="true">*</span>
                                </label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control"  name="val"  value="<?= $data->val ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    商户号
                                    <span class="required" aria-required="true">*</span>
                                </label>
                                <div class="col-md-5">
                                    <input type="text" id="member_id" class="form-control" name="member_id" value="<?= $data->member_id ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    渠道地址
                                    <span class="required" aria-required="true">*</span>
                                </label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control"  name="pay_url" value="<?= $data->pay_url ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    商户密钥
                                </label>
                                <div class="col-md-5">
                                    <input type="text" class="form-control" name="key" value="<?= $data->key ?? ''?>">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    商户公钥
                                </label>
                                <div class="col-md-5">
                                    <textarea name="public_key" class="form-control" rows="4"><?= $data->public_key ?? ''?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">
                                    商户私钥
                                </label>
                                <div class="col-md-5">
                                    <textarea name="private_key" class="form-control" rows="4"><?= $data->private_key ?? ''?></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title">是否开启</label>
                                <div class="col-md-5">
                                    <input type="checkbox" class="make-switch" name="status" <?=  isset($data->status) && $data->status == 1 ? 'checked' : !isset($data->status) ? 'checked': ''?>
                                           data-size="large"  data-on-color="info" data-off-color="success">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label" for="title"></label>
                                <div class="col-md-5">
                                    <button type="button" id="submit" class="btn green btn-circle">
                                        <i class="fa fa-check"></i> 保存
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END CONTENT BODY -->
</div>
