<div class="page-content-wrapper">
    <div class="page-content">
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="/admin/index/index">首页</a>
                    <i class="fa fa-circle"></i>
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12 page-500">
                <div class=" number font-red"> 500 </div>
                <div class=" details">
                    <h3>Oops! Something went wrong.</h3>
                    <p> We are fixing it! Please come back in a while.
                        <br/>
                    </p>
                    <p>
                        <a href="/admin/index/index" class="btn red btn-outline">返回首页 </a>
                        <br>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>