<div class="page-content-wrapper">
    <div class="page-content">

        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="/admin/index/index">首页</a>
                    <i class="fa fa-circle"></i>
                </li>
            </ul>
        </div>
        <div class="row">
            <div class="col-md-12 page-404">
                <div class="number font-green"> 404 </div>
                <div class="details">
                    <h3>Oops! You're lost.</h3>
                    <p> We can not find the page you're looking for.
                        <br/>
                    </p>
                    <p>
                        <a href="/admin/index/index" class="btn green btn-outline">返回首页 </a>
                        <br>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

