<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8"/>
    <title>登录</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
    <link href="{{static_url('assets/global/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{static_url('assets/global/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
    <link href="{{static_url('assets/global/css/components.min.css')}}" rel="stylesheet" id="style_components" type="text/css"/>
    <link href="{{static_url('assets/pages/css/login-2.min.css')}}" rel="stylesheet" type="text/css"/>
    <link rel="shortcut icon" href="favicon.ico"/>
</head>


<body class=" login">
<div class="logo">
    <h3 style="color: #edf4f8;">后台登录系统</h3>
</div>

<div class="content">
    <form class="login-form" method="post">
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">用户名</label>
            <input class="form-control form-control-solid placeholder-no-fix" type="text" id="username"
                   placeholder="用户名" name="username"/></div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">密码</label>
            <input class="form-control form-control-solid placeholder-no-fix" id="password" type="password"
                   placeholder="密码" name="password"/></div>
        <div class="form-actions">
            <button type="button" class="btn red btn-block uppercase" id="submit">登录</button>
        </div>
    </form>
</div>

<script src="{{static_url('assets/global/plugins/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/scripts/app.min.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/pages/scripts/login.js')}}" type="text/javascript"></script>
<script src="{{static_url('assets/global/plugins/layer/layer.js')}}" type="text/javascript"></script>
</body>

</html>