<div class="page-sidebar-wrapper">
    <div class="page-sidebar navbar-collapse collapse">
        <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
            <li class="sidebar-toggler-wrapper hide">
                <div class="sidebar-toggler"> </div>
            </li>
            <li class="nav-item <?= $menu == '/admin/order/index' ? 'active open' : ''?>">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-layers"></i>
                    <span class="title">充值订单</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item <?= $menu == '/admin/order/index' ? 'active open' : ''?>">
                        <a href="/admin/order/index" class="nav-link ">
                            <i class="icon-list"></i>
                            <span class="title">订单列表</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item <?= $menu == '/admin/channel/index' || $menu == '/admin/paytype/index' ? 'active open' : ''?>">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-settings"></i>
                    <span class="title">渠道管理</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item <?= $menu == '/admin/channel/index' ? 'active open' : ''?>">
                        <a href="/admin/channel/index" class="nav-link ">
                            <i class="icon-list"></i>
                            <span class="title">渠道设置</span>
                        </a>
                    </li>
                    <li class="nav-item <?= $menu == '/admin/paytype/index' ? 'active open' : ''?>">
                        <a href="/admin/paytype/index" class="nav-link ">
                            <i class="icon-list"></i>
                            <span class="title">支付类型列表</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item <?= $menu == '/admin/admin/index' ? 'active open' : ''?>">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-user"></i>
                    <span class="title">管理员管理</span>
                    <span class="arrow"></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item <?= $menu == '/admin/admin/index' ? 'active open' : ''?>">
                        <a href="/admin/admin/index" class="nav-link ">
                            <i class="icon-list"></i>
                            <span class="title">管理员列表</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>