

<div class="page-content-wrapper">
    <!-- BEGIN CONTENT BODY -->
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE BAR -->
        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="/admin/index/index">首页</a>
                    <i class="fa fa-circle"></i>
                </li>
                <li>
                    <a href="/admin/order/index">订单列表</a>
                    <i class="fa fa-circle"></i>
                </li>
            </ul>
        </div>
        <!-- END PAGE BAR -->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN EXAMPLE TABLE PORTLET-->
                <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-shopping-cart"></i>订单列表
                        </div>
                    </div>
                    <div class="portlet-body">
                        <div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
                            <form action="/admin/order/index" method="post">
                                <div class="row">
                                    <div class="col-md-3 col-sm-1">
                                        <div id="sample_1_filter" class="dataTables_filter">
                                            <input name="order_id" value="<?= $order_id?>" placeholder="请输入订单号" class="form-control input-sm">
                                        </div>
                                    </div>
                                    <div class="col-md-2 col-sm-3">
                                        <div class="dataTables_length">
                                            <select name="status" value="<?=$order_status?>" class="form-control input-sm input-small">
                                                <option value="" <?= $order_status == '' ? 'selected' : ''?>>请选择状态</option>
                                                <option value="1" <?= $order_status == '1' ? 'selected' : ''?>>支付中</option>
                                                <option value="2" <?= $order_status === '2' ? 'selected' : ''?>>已完成</option>
                                                <option value="3" <?= $order_status === '3' ? 'selected' : ''?>>已失败</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-2 col-sm-3">
                                        <div class="input-group date date-picker">
                                            <input type="text" class="form-control input-sm" readonly id="start_time" value="<?= $start_time?>"  name="start_time" placeholder="请选择开始日期">
                                            <span class="input-group-btn">
                                                <button class="btn btn-sm default" type="button">
                                                    <i class="fa fa-calendar"></i>
                                                </button>
                                            </span>
                                        </div>
                                        <div class="input-group date date-picker margin-bottom-40">
                                            <input type="text" class="form-control input-sm" readonly id="end_time" value="<?= $end_time?>"  name="end_time" placeholder="请选择结束日期">
                                            <span class="input-group-btn">
                                                <button class="btn btn-sm default" type="button">
                                                    <i class="fa fa-calendar"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-md-2 col-sm-0">
                                       <div class="margin-bottom-5">
                                           <button class="btn btn-sm btn blue filter-submit margin-bottom">
                                               <i class="fa fa-search"></i> 搜索
                                           </button>
                                       </div>
                                    </div>
                                </div>
                                <div class="table-container">
                                    <table class="table table-striped table-bordered table-hover table-checkable" id="datatable_products">
                                        <thead>
                                        <tr role="row" class="heading">
                                            <th width="10%"> ID</th>
                                            <th width="15%"> 订单ID</th>
                                            <th width="15%"> 金额(元)</th>
                                            <th width="10%"> 支付方式</th>
                                            <th width="10%"> 状态</th>
                                            <th width="15%"> 渠道</th>
                                            <th width="10%"> 创建时间</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php foreach ($page->items as $order): ?>
                                            <tr role="row" class="odd">
                                                <td class="sorting_1"><?= $order->id ?></td>
                                                <td><?= $order->order_id ?></td>
                                                <td><?= $order->amount ?></td>
                                                <td><?= $pay_type[$order->pay_type] ?></td>
                                                <td>
                                                    <span class="label label-sm
                                                    <?php
                                                        if ($order->status == 0) {
                                                            echo 'label-success';
                                                        } elseif ($order->status == 1) {
                                                            echo 'label-danger';
                                                        } elseif ($order->status == 2) {
                                                            echo 'label-info';
                                                        }
                                                    ?>"><?= $status[$order->status] ?>
                                                    </span>
                                                </td>
                                                <td><?= $channel[$order->type] ?></td>
                                                <td><?= date('Y-m-d H:i:s', $order->created_at) ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="row">
                                    <div class="col-md-5 col-sm-5">
                                        <div class="dataTables_info" id="sample_1_info" role="status" aria-live="polite">
                                            总条数：<?= $page->total_pages?>
                                        </div>
                                    </div>
                                    <?php if($page->total_pages > 1):?>
                                        <div class="col-md-7 col-sm-7">
                                            <div class="dataTables_paginate paging_bootstrap_full_number" id="sample_1_paginate">
                                                {{ page.paginator_render }}
                                            </div>
                                        </div>
                                    <?php endif;?>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- END EXAMPLE TABLE PORTLET-->
            </div>
        </div>
    </div>
    <!-- END CONTENT BODY -->
</div>
